debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.acorn_mentor.acorn_mentor: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


spring:
  datasource:
#    mysql 주소
    url: jdbc:mysql://localhost:3306/board
    username: jiwoo
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

#   h2 주소
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    # spring 3.1.0 dialect ??
#    database: mysql
#    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql : true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always
  # thymeleaf.cache: false
  data.rest:
    base-path: /api
    detection-strategy: annotated

---

spring:
  config.activate.on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driverClassName: org.h2.Driver
  sql.init.mode: always
  h2.console.enabled: true
#  test.database.replace: none


