insert into user_account(user_id, user_pw, nickname, email, created_date, created_by, modified_date, modified_by) values ('jiwoo', '1234', 'jiwoo', ' jiwoo@naver.com', now(), 'jiwoo', now(), 'jiwoo');
insert into user_account(user_id, user_pw, nickname, email, created_date, created_by, modified_date, modified_by) values ('wonhee', '1234', 'wonhee', ' wonhee@naver.com', now(), 'wonhee', now(), 'wonhee');

insert into post(user_account_user_id, title, content, hashtag, created_date, created_by, modified_date, modified_by) values ('wonhee', '난 아가야', '응애 나 아가 나 운빨충', 'Mauv', '2023-06-18 05:36:52', 'Ignazio', '2022-07-01 01:45:43', 'Edeline');
insert into post(user_account_user_id, title, content, hashtag, created_date, created_by, modified_date, modified_by) values ('jiwoo', 'quam', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Green', '2023-03-28 08:57:23', 'Leanor', '2022-07-03 15:14:46', 'Cass');
insert into post(user_account_user_id, title, content, hashtag, created_date, created_by, modified_date, modified_by) values ('jiwoo', 'in', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'Goldenrod', '2022-07-04 03:59:18', 'Siffre', '2022-11-01 02:29:32', 'Lexi');
insert into post(user_account_user_id, title, content, hashtag, created_date, created_by, modified_date, modified_by) values ('jiwoo', 'nulla', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 'Teal', '2022-07-17 06:52:56', 'Vin', '2022-09-15 08:14:21', 'Cordie');

insert into comment (post_id, user_account_user_id, content, created_date, created_by, modified_date, modified_by) values (1, 'jiwoo', 'trumpet','2022-11-01 05:36:52', 'admin', '2022-11-01 05:36:52', 'admin');
insert into comment (post_id, user_account_user_id, content, created_date, created_by, modified_date, modified_by) values (1, 'jiwoo', 'guitar','2022-11-01 05:36:52', 'admin', '2022-11-01 05:36:52', 'admin');
insert into comment (post_id, user_account_user_id, content, created_date, created_by, modified_date, modified_by) values (2, 'jiwoo', 'drum','2022-11-01 05:36:52', 'admin', '2022-11-01 05:36:52', 'admin');
insert into comment (post_id, user_account_user_id, content, created_date, created_by, modified_date, modified_by) values (2, 'jiwoo', 'violin','2022-11-01 05:36:52', 'admin', '2022-11-01 05:36:52', 'admin');
insert into comment (post_id, user_account_user_id, content, created_date, created_by, modified_date, modified_by) values (3, 'jiwoo', 'piano','2022-11-01 05:36:52', 'admin', '2022-11-01 05:36:52', 'admin');